export const payFwddata = [
  {
    id: 1,
    personsPaidFor: "5",
    processingPpl: "5",
    amount: "$10",
    content1: "What is the difference between pay it forward and investing?",
    content2: "Translate into new languages",
    content3: "Pay it forward",
  },
  {
    id: 2,
    personsPaidFor: "15",
    processingPpl: "15",
    amount: "$20",
    content1: "What is the difference between pay it forward and investing?",
    content2: "Translate into new languages",
    content3: "Pay it forward",
  },
  {
    id: 3,
    personsPaidFor: "50",
    processingPpl: "50",
    amount: "$50",
    content1: "What is the difference between pay it forward and investing?",
    content2: "Translate into new languages",
    content3: "Pay it forward",
  },
  {
    id: 4,
    personsPaidFor: "150",
    processingPpl: "150",
    amount: "$100",
    content1: "What is the difference between pay it forward and investing?",
    content2: "Translate into new languages",
    content3: "Pay it forward",
  },
  {
    id: 5,
    personsPaidFor: "400",
    processingPpl: "400",
    amount: "$250",
    content1: "What is the difference between pay it forward and investing?",
    content2: "Translate into new languages",
    content3: "Pay it forward",
  },
  {
    id: 6,
    personsPaidFor: "5.6k",
    processingPpl: "5600",
    amount: "$1000",
    content1: "What is the difference between pay it forward and investing?",
    content2: "Translate into new languages",
    content3: "Pay it forward",
  },
];
